name: Checkout
description: Check out Multipass code along with tags and submodules

runs:
  using: composite
  steps:
  - name: Check out submodules
    shell: bash
    run: |
      git submodule sync
      # This repository can't do depth.
      git -c protocol.version=2 submodule update --init 3rd-party/xz-decoder/xz-embedded
      git -c protocol.version=2 submodule update --init --force --depth=1 --recursive

  - name: Fetch tags
    shell: bash
    run: |
      git fetch --recurse-submodules origin +refs/tags/*:refs/tags/*

  - name: Read vcpkg.json file into a variable
    shell: bash
    id: read-vcpkg-json
    run: |
      echo "content<<EOF" >> $GITHUB_OUTPUT
      cat ./vcpkg.json >> $GITHUB_OUTPUT
      echo "EOF" >> $GITHUB_OUTPUT

  - name: Fetch the vcpkg builtin-baseline
    shell: bash
    run: |

      cd 3rd-party/vcpkg
      # Read the builtin-baseline from the vcpkg.json
      BASELINE=${{ fromJSON(steps.read-vcpkg-json.outputs.content)['builtin-baseline'] }}
      # Let's check if the head is already at the baseline.
      if [ "$(git rev-parse HEAD)" = "$BASELINE" ]; then
        echo "HEAD is at BASELINE, there is no work to be done."
        exit 0
      fi
      echo "Found builtin-baseline: $BASELINE"
      #
      # Fetch the baseline commit. We only need its timestamp, so fetch it solely.
      git fetch origin $BASELINE --depth=1
      #
      # Use baseline commit's timestamp to do a shallow-since pull to only fetch
      # the commits we're actually going to need. So the final branch will contain
      # <submodule-commit>~<baseline-commit>, inclusive. GitHub does not seem to like
      # `--shallow-exclude` and just rejects it, so we're using shallow-since as an
      # alternate solution. `git fetch --unshallow` also works but it fetches everything.
      #
      # With `git fetch --unshallow` the checkout job takes 1m 40s whereas the shallow-since
      # approach reduces that to takes 39 seconds.
      #
      git pull --shallow-since=$(git show -s --format=%at "$BASELINE") origin master
