#!/usr/bin/env python3
"""Generates packaging/gui-less/snap/snapcraft.yaml from snap/snapcraft.yaml.
The transformations here are the authoritative definition of how the gui-less
variant differs from the main snap.

Usage:
    ./generate-snapcraft.py          # regenerate packaging/gui-less/snap/snapcraft.yaml
    ./generate-snapcraft.py --check  # verify it's up to date (for CI)
"""

import argparse
import re
import subprocess
import sys
from pathlib import Path

from ruamel.yaml import YAML
from ruamel.yaml.scalarstring import LiteralScalarString

SCRIPT_DIR = Path(__file__).parent
INPUT = SCRIPT_DIR / "../../snap/snapcraft.yaml"
OUTPUT = SCRIPT_DIR / "snap/snapcraft.yaml"

MULTIPASS_SOURCE = "https://github.com/canonical/multipass.git"
HEADER = (
    "Generated by packaging/gui-less/generate-snapcraft.py — do not edit directly.\n"
    "# Edit snap/snapcraft.yaml and re-run the script."
)


def generate(input_path: Path, output_path: Path) -> None:
    yaml = YAML()
    yaml.preserve_quotes = True
    yaml.width = 4096

    data = yaml.load(input_path)

    # Add architectures for gui-less snap
    data["platforms"]["s390x"] = None
    data["platforms"]["ppc64el"] = None

    # Remove the GUI app
    del data["apps"]["gui"]

    # Change multipass part to use remote git source
    data["parts"]["multipass"]["source"] = MULTIPASS_SOURCE

    # Use a CMake preset to turn off the GUI
    data["parts"]["multipass"]["build-environment"].append(
        {"CMAKE_PRESET": "snap-gui-less"}
    )

    # Change glue part to clone snap-wrappers from remote git source
    glue = data["parts"]["glue"]
    glue["source"] = MULTIPASS_SOURCE
    glue["source-type"] = "git"
    glue["source-subdir"] = "snap-wrappers"

    data.yaml_set_start_comment(HEADER)

    with output_path.open("w") as f:
        yaml.dump(data, f)


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="verify the output is up to date (for CI)")
    args = parser.parse_args()

    if not INPUT.exists():
        print(f"ERROR: source file not found: {INPUT}", file=sys.stderr)
        sys.exit(1)

    generate(INPUT.resolve(), OUTPUT.resolve())

    if args.check:
        result = subprocess.run(
            ["git", "diff", "--exit-code", "snap/snapcraft.yaml"],
            cwd=SCRIPT_DIR,
        )
        if result.returncode != 0:
            print(
                "ERROR: packaging/gui-less/snap/snapcraft.yaml is out of date.\n"
                "Run packaging/gui-less/generate-snapcraft.py to update it.",
                file=sys.stderr,
            )
            sys.exit(1)
        print("packaging/gui-less/snap/snapcraft.yaml is up to date.")


if __name__ == "__main__":
    main()
