[project]
name = "multipass-cli-tests"
version = "1.0.0"
readme = "README.md"
dependencies = ["pytest", "pexpect", "jq", "pywinpty; sys_platform == 'win32'"]

# This project is not intended for packaging.
[tool.setuptools]
py-modules = []

[tool.pylint."MESSAGES CONTROL"]
disable = ["logging-fstring-interpolation"]

[tool.pytest.ini_options]
filterwarnings = ["ignore:.*multi-threaded.*forkpty.*:DeprecationWarning"]
markers = [
    "snapshot: Snapshot tests.",
    "clone: Clone tests.",
    "slow: The tests that known to have a slow run time.",
    "lifecycle: Basic VM lifecycle tests.",
    "mount: Mount tests.",
    "resource: VM resource modification tests"
]
