name: Determine build parameters
description: Determine Multipass build parameters (labels, snap channels etc.)

inputs:
  release-branch-re:
    description: "Release branch pattern"
    default: ^refs/heads/release/[0-9\.]+$
  release-tag-re:
    description: "Release tag pattern"
    default: ^refs/tags/v[0-9]+\.[0-9]+\.[0-9]+$

outputs:
  label:
    description: Label to annotate the build version with
    value: ${{ steps.build-params.outputs.label }}
  channel:
    description: Snap channel to publish to
    value: ${{ steps.build-params.outputs.channel }}

runs:
  using: composite

  steps:
  - name: Determine build parameters
    id: build-params
    shell: bash
    #prevent (shell) code injection
    env:
      EVENT_NAME: ${{ github.event_name }}
      GIT_REF: ${{ github.ref }}
      PR_NUMBER: ${{ github.event.number }}
      RUN_NUMBER: ${{ github.run_number }}
      RELEASE_BRANCH_RE: ${{ inputs.release-branch-re }}
      RELEASE_TAG_RE: ${{ inputs.release-tag-re }}
    run: |
      # If it's a pull request or `trying` push, annotate with `pr#` and publish to `edge/pr#`.
      if [ "$EVENT_NAME" == "pull_request" ]; then
        echo "label=pr${PR_NUMBER}" >> "$GITHUB_OUTPUT"
        echo "channel=edge/pr${PR_NUMBER}" >> "$GITHUB_OUTPUT"

      # If it's a merge group, annotate with `ci#` and publish to `edge/ci#`.
      elif [ "$EVENT_NAME" == "merge_group" ]; then
        echo "label=ci${RUN_NUMBER}" >> "$GITHUB_OUTPUT"
        echo "channel=edge/ci${RUN_NUMBER}" >> "$GITHUB_OUTPUT"

      # If it's a release tag or branch, publish to the `beta` channel.
      elif [[ "$GIT_REF" =~ $RELEASE_BRANCH_RE || "$GIT_REF" =~ $RELEASE_TAG_RE ]]; then
        echo "channel=beta" >> "$GITHUB_OUTPUT"

      # All other events annotate with the CI run number.
      # This includes `main`, as `edge` will get published from automatic builds on snapcraft.io.
      else
        echo "label=ci${RUN_NUMBER}" >> "$GITHUB_OUTPUT"
      fi
