name: Lint
description: Run Linting steps

runs:
  using: composite
  steps:
  - name: Check for forbidden tag in code
    shell: bash
    run: |
      set -e -o pipefail

      # On pull requests, HEAD^1 will always be the merge base, so diff against that. Look for forbidden strings,
      # but exclude legitimate cases.
      forbidden_regex='(?i)\bno[_-]?merge\b'
      added_regex="^\+.*${forbidden_regex}" # we care only about additions
      git diff -U0 --no-color HEAD^1 -- . ':(exclude)bors.toml' |
        (grep -P "${added_regex}" || true) |
        tee ${HOME}/forbidden_occurrences
      if [ "$( stat --printf='%s' ${HOME}/forbidden_occurrences )" -ne 0 ]; then
        echo "##[error] Forbidden string(s) found in the diff ^ (matched \"$added_regex\")"
        exit 1
      fi

  - name: Check whitespace
    uses: ./.github/actions/whitespace

  - name: Check final newline
    uses: qwrtln/check-final-newline@v1.0.0

  - name: Install clang-format
    shell: bash
    run: sudo apt-get install --no-install-recommends --yes clang-format-16

  - name: Run clang-format through the diff
    shell: bash
    run: |
      set -e -o pipefail

      # On pull requests, HEAD^1 will always be the merge base, so consider that diff for formatting.
      git diff -U0 --no-color HEAD^1 | clang-format-diff-16 -p1 | tee ${HOME}/clang-diff
      if [ "$( stat --printf='%s' ${HOME}/clang-diff )" -ne 0 ]; then
        echo "##[error] Please apply the above diff to correct formatting"
        exit 1
      fi

  - name: Initialize Flutter submodule and verify installation
    shell: bash
    run: |
      set -e -o pipefail
      git submodule update --init 3rd-party/flutter
      if [ ! -f "3rd-party/flutter/bin/dart" ]; then
        echo "##[error] Flutter submodule not initialized. Run 'git submodule update --init 3rd-party/flutter' to fix this issue."
        exit 1
      fi

  - name: Run Flutter format check
    shell: bash
    run: |
      set -e -o pipefail
      if ! 3rd-party/flutter/bin/dart format --output=none --set-exit-if-changed src/client/gui; then
        echo "##[error] Flutter code is not properly formatted. Run '3rd-party/flutter/bin/dart format' to fix formatting."
        exit 1
      fi
