name: Lint
description: Run Linting steps

runs:
  using: composite
  steps:
  - name: Check for forbidden tag in code
    shell: bash
    run: |
      set -e -o pipefail

      # On pull requests, HEAD^1 will always be the merge base, so diff against that. Look for forbidden strings,
      # but exclude legitimate cases.
      forbidden_regex='(?i)\bno[_-]?merge\b'
      added_regex="^\+.*${forbidden_regex}" # we care only about additions
      git diff -U0 --no-color HEAD^1 -- . ':(exclude)bors.toml' |
        (grep -P "${added_regex}" || true) |
        tee ${HOME}/forbidden_occurrences
      if [ "$( stat --printf='%s' ${HOME}/forbidden_occurrences )" -ne 0 ]; then
        echo "##[error] Forbidden string(s) found in the diff ^ (matched \"$added_regex\")"
        exit 1
      fi

  - name: Install clang-format
    shell: bash
    run: sudo apt-get install --no-install-recommends --yes clang-format-12

  - name: Run clang-format through the diff
    shell: bash
    run: |
      set -e -o pipefail

      # On pull requests, HEAD^1 will always be the merge base, so consider that diff for formatting.
      git diff -U0 --no-color HEAD^1 | clang-format-diff-12 -p1 | tee ${HOME}/clang-diff
      if [ "$( stat --printf='%s' ${HOME}/clang-diff )" -ne 0 ]; then
        echo "##[error] Please apply the above diff to correct formatting"
        exit 1
      fi
