name: multipass
title: Multipass
icon: data/multipass.gui.svg
summary: Instant Ubuntu VMs
description: |
  Multipass is a tool to launch and manage VMs on Windows, Mac and Linux that
  simulates a cloud environment with support for cloud-init. Get Ubuntu
  on-demand with clean integration to your IDE and version control on your
  native platform.
license: GPL-3.0

adopt-info: multipass
confinement: strict
base: core22

architectures:
  - build-on: amd64
  - build-on: arm64

layout:
  /usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/qemu:
    bind: $SNAP/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/qemu
  /usr/share/X11:
    bind: $SNAP/usr/share/X11
  /etc/fonts:
    bind: $SNAP/etc/fonts
  /usr/share/fonts:
    bind: $SNAP/usr/share/fonts
  /usr/share/icons:
    bind: $SNAP/usr/share/icons

environment:
  # GDK pixbuf
  GDK_PIXBUF_MODULEDIR: $SNAP/usr/lib/${CRAFT_ARCH_TRIPLET_BUILD_FOR}/gdk-pixbuf-2.0/2.10.0/loaders
  GDK_PIXBUF_MODULE_FILE: $SNAP_COMMON/loaders.cache
  ARCH_TRIPLET: ${CRAFT_ARCH_TRIPLET_BUILD_FOR}

plugs:
  all-home:
    interface: home
    read: all

apps:
  multipassd:
    command: bin/launch-multipassd
    environment:
      LD_LIBRARY_PATH: &library-path
        $SNAP/lib:$SNAP/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR:$SNAP/usr/lib:$SNAP/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR
      PATH: &path
        $SNAP/usr/sbin:$SNAP/usr/bin:$SNAP/sbin:$SNAP/bin:$PATH
      QT_PLUGIN_PATH: $SNAP/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/qt6/plugins
      XDG_DATA_HOME: $SNAP_COMMON/data
      XDG_CACHE_HOME: $SNAP_COMMON/cache
      XDG_CONFIG_HOME: &daemon-config $SNAP_DATA/config
      DAEMON_CONFIG_HOME: *daemon-config # temporary
    daemon: simple
    stop-timeout: 5m
    plugs:
      - all-home
      - firewall-control
      - kvm
      - libvirt
      - multipass-support
      - network-bind
      - network-control
      - network-manager # for bridge creation
      - network-observe # for network listing (to read `/sys/devices/**/net/*`)
      - lxd
      - removable-media
      - system-observe  # to read the host's os-release
  multipass:
    environment:
      <<: &client-environment
        LD_LIBRARY_PATH: *library-path
        PATH: *path
        QT_PLUGIN_PATH: $SNAP/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/qt6/plugins
        XDG_DATA_HOME: $SNAP_USER_DATA/data
        XDG_DATA_DIRS: $SNAP/usr/share:$SNAP_DATA/data
        XDG_CACHE_HOME: $SNAP_USER_DATA/cache
        XDG_CONFIG_HOME: $SNAP_USER_DATA/config
      DAEMON_CONFIG_HOME: *daemon-config # temporary
    command: bin/launch-multipass
    completer: etc/bash_completion.d/snap.multipass
    plugs:
      - all-home
      - network
  gui:
    desktop: usr/share/applications/multipass.gui.desktop
    autostart: multipass.gui.autostart.desktop
    extensions: [ gnome ]
    environment: &_client-environment
      XDG_DATA_HOME: $SNAP_USER_DATA
      XDG_DATA_DIRS: $SNAP/usr/share
    command: bin/bundle/multipass_gui
    command-chain: [bin/set-xdg-vars]
    plugs:
      - all-home
      - desktop
      - desktop-legacy
      - gsettings
      - network
      - opengl
      - removable-media
      - unity7
      - wayland
      - x11

parts:
  libvirt:
    plugin: nil
    stage-packages:
    - libvirt0
    stage:
    - -usr/lib/*/libssh*  # this avoids extra libssh libs in the snap
    - -usr/lib/*/libvirt-* # No need to include extra libvirt objects in snap
    - -usr/lib/**/sasl2
    - -usr/lib/*/libicuio.so.*
    - -usr/lib/*/libicutest.so.*
    - -usr/lib/*/libicutu.so.*
    - -usr/share/doc*
    - -usr/share/libvirt
    - -usr/share/lintian

  qt-ssl-plugin:
    plugin: nil
    stage-packages:
    - qt6-qpa-plugins
    prime:
    - usr/lib/*/qt6/plugins/tls/*

  multipass:
    after: [ qt-ssl-plugin ]
    plugin: cmake
    build-snaps:
    - cmake
    build-environment:
    - PATH: /snap/bin:$PATH
    - VCPKG_FORCE_SYSTEM_BINARIES: 1
    build-packages:
    - on arm64: [libgles2-mesa-dev]
    - build-essential
    - git
    - libapparmor-dev
    - libgl1-mesa-dev
    - libsystemd-dev
    - libssl-dev
    - libvirt-dev
    - pkg-config
    - qt6-base-dev
    - qt6-base-dev-tools
    - zip
    - unzip
    - curl
    - libkeybinder-3.0-dev
    - clang
    - ninja-build
    stage-packages:
    - apparmor
    - libpng16-16
    - libqt6core6
    - libqt6network6
    - libssl3
    - libxml2
    - dnsmasq-base
    - dnsmasq-utils
    - libgdk-pixbuf2.0-bin
    - libglib2.0-0
    - libgtk-3-0
    - libkeybinder-3.0-dev
    stage:
    - -**/glvnd
    - -**/X11
    - -usr/bin/aa-*
    - -usr/include
    - -usr/lib/cmake
    - -usr/lib/*/libEGL_mesa.so.*
    - -usr/lib/*/libgirepository-1.0.so.*
    - -usr/lib/*/libgthread-2.0.so*
    - -usr/lib/*/libGLX_mesa.so.*
    - -usr/lib/*/libGLX_indirect.so.*
    - -usr/lib/*/libXxf86vm.so.*
    - -usr/lib/*/libxcb-dri2.so.*
    - -usr/lib/*/libxcb-present.so.*
    - -usr/lib/*/libxshmfence.so.*
    - -usr/lib/*/libicuio.so.*
    - -usr/lib/*/libicutest.so.*
    - -usr/lib/*/libicutu.so.*
    - -usr/lib/*/libLLVM-15.so*
    - -usr/lib/*/libdrm*
    - -usr/lib/*/libglapi.so*
    - -usr/lib/*/libpciaccess.so*
    - -usr/lib/*/libsensors.so*
    - -usr/lib/*/libxcb-dri3.so*
    - -usr/lib/*/dri
    - -usr/lib/${CRAFT_ARCH_TRIPLET_BUILD_FOR}/libcolordprivate.so.*
    - -usr/lib/${CRAFT_ARCH_TRIPLET_BUILD_FOR}/libdconf.so.*
    - -usr/share/apport
    - -usr/share/bug
    - -usr/share/doc*
    - -usr/share/drirc.d
    - -usr/share/gettext
    - -usr/share/icons/Adwaita
    - -usr/share/icons/DMZ-Black
    - -usr/share/icons/Humanity*
    - -usr/share/icons/LoginIcons
    - -usr/share/icons/hicolor
    - -usr/share/icons/ubuntu-*
    - -usr/share/lib*
    - -usr/share/lintian
    - -usr/share/man
    - -usr/share/mime
    - -usr/share/pkgconfig
    - -usr/share/thumbnailers
    prime:
    - -protobuf
    source: .
    cmake-parameters:
    - -DCMAKE_BUILD_TYPE=Release
    - -DCMAKE_INSTALL_PREFIX=/
    - -DMULTIPASS_ENABLE_TESTS=off
    - -DMULTIPASS_UPSTREAM=origin
    - -DMULTIPASS_ENABLE_FLUTTER_GUI=on
    override-build: |
      craftctl default
      set -e
      mkdir -p ${CRAFT_PART_INSTALL}/etc/bash_completion.d/
      echo 'export PATH="${PATH}:/snap/bin:/var/lib/snapd/snap/bin"' > ${CRAFT_PART_INSTALL}/etc/bash_completion.d/snap.multipass
      cat ../src/completions/bash/multipass >> ${CRAFT_PART_INSTALL}/etc/bash_completion.d/snap.multipass
      VERSION=$( awk -F\" '/version_string/ { print $2 }' gen/multipass/version.h )
      craftctl set version=${VERSION}
      craftctl set grade=$( echo ${VERSION} | grep -qe '^[0-9]\+\.[0-9]\+\.[0-9]\+\($\|-rc\)' && echo stable || echo devel )
      sed -i -e 's@^Icon=\(.\+\)$@Icon=/usr/share/icons/hicolor/scalable/apps/\1.svg@' ${CRAFT_PART_INSTALL}/usr/share/applications/multipass.gui.desktop

      cd ${CRAFT_PART_SRC}/3rd-party
      find . -name 'LICENSE*' -print0 | xargs -0 -I FILE install --mode=644 -D --no-target-directory FILE ${CRAFT_PART_INSTALL}/licenses/FILE

  qemu:
    build-environment:
    - LD_LIBRARY_PATH: ""
    - XDG_DATA_DIRS: /root/stage/usr/share:/usr/share
    - PKG_CONFIG_PATH: ""
    source: https://github.com/canonical/qemu.git
    source-type: git
    source-branch: multipass-8.2.1+9p-uid-gid-map
    source-depth: 1
    source-submodules: []
    plugin: autotools
    autotools-configure-parameters:
    - --enable-virtfs
    - --disable-bochs
    - --disable-cloop
    - --disable-docs
    - --disable-guest-agent
    - --disable-parallels
    - --disable-qed
    - --disable-libiscsi
    - --disable-vnc
    - --disable-xen
    - --disable-dmg
    - --disable-replication
    - --disable-snappy
    - --disable-lzo
    - --disable-live-block-migration
    - --disable-vvfat
    - --disable-curl
    - --disable-tests
    - --disable-nettle
    - --disable-libusb
    - --disable-bzip2
    - --disable-gcrypt
    - --disable-gnutls
    - --disable-slirp
    - --disable-user
    - --disable-libvduse
    - --disable-vduse-blk-export
    - --firmwarepath=/snap/multipass/current/qemu/
    - --prefix=/usr
    - --libdir=/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR
    - --libexecdir=/usr/lib/qemu
    - --enable-strip
    build-packages:
    - libattr1-dev
    - libcap-ng-dev
    - libglib2.0-dev
    - libpixman-1-dev
    - libseccomp-dev
    - meson
    - python3-venv
    stage-packages:
    - libpixman-1-0
    stage:
    - -usr/include
    - -usr/lib/*/libssh*
    - -qemu/efi-*.rom
    - -qemu/pxe-*.rom
    organize:
      usr/lib/qemu/*: usr/bin/
      usr/share/qemu/*: qemu/
    override-pull: |-
      [ "$(uname -m)" != "x86_64" ] && [ "$(uname -m)" != "aarch64" ] && exit 0

      craftctl default
    override-build: |-
      [ "$(uname -m)" != "x86_64" ] && [ "$(uname -m)" != "aarch64" ] && exit 0

      set -ex
      # Mangle the configure a bit
      QEMUARCH="$(uname -m)"
      sed -i "s/^unset target_list$/target_list=\"${QEMUARCH}-softmmu\"/" configure

      set +ex
      craftctl default
    prime:
    - usr/bin/qemu-system-*
    - usr/bin/qemu-img*
    - usr/bin/virtfs-proxy-helper*
    - usr/bin/virtiofsd*
    - usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/*
    - lib/*/libpixman*so*
    - qemu/keymaps*
    - qemu/efi-virtio.rom*
    - qemu/kvmvapic.bin*
    - qemu/vgabios-*.bin*
    - qemu/slof.bin*
    - qemu/bios-256k.bin*
    - -usr/lib/*/pkgconfig

  qemu-firmware:
    plugin: nil
    override-pull: ""
    stage-packages:
    - ipxe-qemu
    - on amd64: [ovmf]
    - on arm64: [qemu-efi]
    organize:
      usr/share/ovmf/*: qemu/
      usr/lib/ipxe/qemu/*: qemu/
      usr/share/qemu-efi-aarch64/*: qemu/
    prime:
    - qemu/*

  kvm-support:
    plugin: nil
    override-pull: ""
    stage-packages:
    - on amd64: [msr-tools]
    stage:
    - -usr/share/doc
    - -usr/share/man

  compile-schemas:
    plugin: nil
    stage-packages:
    - libglib2.0-0
    prime:
    - usr/lib/${CRAFT_ARCH_TRIPLET_BUILD_FOR}/glib-2.0/glib-compile-schemas

  glue:
    plugin: dump
    source: snap-wrappers
