name: multipass
version: '2017.0.0'
version-script: |
  git describe
summary: Ubuntu at your fingertips
description: |
  Multipass gives you Ubuntu VMs in seconds. Just run `multipass launch`
  and it'll do all the setup for you. Check out `multipass find` for a list
  of available images. More details you can find under `multipass help`.

grade: devel
confinement: classic

apps:
  multipassd:
    command: bin/launch-multipassd
    environment:
      LD_LIBRARY_PATH: $SNAP/lib/x86_64-linux-gnu:$SNAP/usr/lib/x86_64-linux-gnu::$SNAP/lib:$SNAP/usr/lib:$SNAP/lib/x86_64-linux-gnu:$SNAP/usr/lib/x86_64-linux-gnu
      PATH: $SNAP/usr/sbin:$SNAP/usr/bin:$SNAP/sbin:$SNAP/bin:$PATH
      QT_PLUGIN_PATH: $SNAP/usr/lib/x86_64-linux-gnu/qt5/plugins
      XDG_DATA_HOME: $SNAP_COMMON/data
      XDG_CACHE_HOME: $SNAP_COMMON/cache
    daemon: simple
  multipass:
    environment:
      LD_LIBRARY_PATH: $SNAP/lib/x86_64-linux-gnu:$SNAP/usr/lib/x86_64-linux-gnu::$SNAP/lib:$SNAP/usr/lib:$SNAP/lib/x86_64-linux-gnu:$SNAP/usr/lib/x86_64-linux-gnu
      PATH: $SNAP/usr/sbin:$SNAP/usr/bin:$SNAP/sbin:$SNAP/bin:$PATH
      QT_PLUGIN_PATH: $SNAP/usr/lib/x86_64-linux-gnu/qt5/plugins
    command: bin/multipass
    completer: etc/bash_completion.d/snap.multipass

parts:
  qtbase5-dev:
    after: [qt5-qmake-bin]
    plugin: dump
    source: http://archive.ubuntu.com/ubuntu/pool/main/q/qtbase-opensource-src/qtbase5-dev_5.9.3+dfsg-0ubuntu1_amd64.deb
    source-type: deb
    source-checksum: sha256/f3df1b823cc0c96305442671b595544f1e21d8fa63ede3c685ffd73447ff19cb
    prime: [-*]

  qtbase5-dev-tools:
    plugin: dump
    source: http://archive.ubuntu.com/ubuntu/pool/main/q/qtbase-opensource-src/qtbase5-dev-tools_5.9.3+dfsg-0ubuntu1_amd64.deb
    source-type: deb
    source-checksum: sha256/949021e04ef908a1c23354b46e06a58701bd7a0185a96e1180cab0a822dc6739
    prime: [-*]

  qt5-qmake:
    plugin: dump
    source: http://archive.ubuntu.com/ubuntu/pool/main/q/qtbase-opensource-src/qt5-qmake_5.9.3+dfsg-0ubuntu1_amd64.deb
    source-type: deb
    source-checksum: sha256/22719164c2374dd55f560ec4b4d03660e9df6ee5a6d58d212cf48e75fcd255d3
    prime: [-*]

  qt5-qmake-bin:
    after: [qt5-qmake]
    plugin: dump
    source: http://archive.ubuntu.com/ubuntu/pool/main/q/qtbase-opensource-src/qt5-qmake-bin_5.9.3+dfsg-0ubuntu1_amd64.deb
    source-type: deb
    source-checksum: sha256/9ff4332f6376e4ae19a2c5db2c459905e067b31710e65f5377da2e64c219ff25
    prime: [-*]

  libqt5core5a:
    after: [libicu]
    plugin: dump
    source: http://archive.ubuntu.com/ubuntu/pool/main/q/qtbase-opensource-src/libqt5core5a_5.9.3+dfsg-0ubuntu1_amd64.deb
    source-type: deb
    source-checksum: sha256/99e0d91d74df53b66db643bc65ebeba5b8318d78da28bbab603cb5e3d8cff2fd
    stage-packages:
    - libdouble-conversion1v5
    - libpcre16-3

  libqt5dbus5:
    plugin: dump
    source: http://archive.ubuntu.com/ubuntu/pool/main/q/qtbase-opensource-src/libqt5dbus5_5.9.3+dfsg-0ubuntu1_amd64.deb
    source-type: deb
    source-checksum: sha256/d97102016742d09319d892f462a312fda5f859610dbabcc22a83173979f3bd4e

  libqt5network5:
    plugin: dump
    source: http://archive.ubuntu.com/ubuntu/pool/main/q/qtbase-opensource-src/libqt5network5_5.9.3+dfsg-0ubuntu1_amd64.deb
    source-type: deb
    source-checksum: sha256/7cfc6548963ba4facbd05f4a223b0ebf0d3ee30c421cd0af056d5a69e405645d
    stage-packages:
    - libproxy1v5

  libicu:
    plugin: dump
    source: http://archive.ubuntu.com/ubuntu/pool/main/i/icu/libicu60_60.2-1ubuntu1_amd64.deb
    source-type: deb
    source-checksum: sha256/0ef7f85757b576a38a04fd768bcc00df55eb7590fbb4e996104985e1ea47b153

  multipass:
    after:
    - qtbase5-dev
    - qtbase5-dev-tools
    - libqt5core5a
    - libqt5network5
    plugin: cmake
    build-packages:
    - build-essential
    - cmake-extras
    - golang
    source: .
    configflags:
    - -DCMAKE_BUILD_TYPE=RelWithDebInfo
    - -DCMAKE_INSTALL_PREFIX=/
    - -DMULTIPASS_ENABLE_TESTS=off
    install: |-
      set -ex
      mkdir -p ${SNAPCRAFT_PART_INSTALL}/etc/bash_completion.d/
      echo 'export PATH="${PATH}:/snap/bin:/var/lib/snapd/snap/bin"' > ${SNAPCRAFT_PART_INSTALL}/etc/bash_completion.d/snap.multipass
      cat ../src/completions/bash/multipass >> ${SNAPCRAFT_PART_INSTALL}/etc/bash_completion.d/snap.multipass

  qemu:
    plugin: nil
    stage-packages:
    - qemu-system-x86
    - qemu-utils
    - libslang2
    organize:
      usr/lib/x86_64-linux-gnu/pulseaudio/libpulsecommon-8.0.so: usr/lib/x86_64-linux-gnu/libpulsecommon-8.0.so
      usr/share/seabios/bios-256k.bin: qemu/bios-256k.bin
      usr/share/seabios/vgabios-stdvga.bin: qemu/vgabios-stdvga.bin
      usr/share/seabios/kvmvapic.bin: qemu/kvmvapic.bin
      usr/lib/ipxe/qemu/efi-virtio.rom: qemu/efi-virtio.rom

  dnsmasq:
    plugin: nil
    stage-packages:
    - dnsmasq

  kvm-support:
    plugin: nil
    stage-packages:
    - msr-tools

  glue:
    plugin: dump
    source: snap
