name: cla-check
on:
  pull_request:
  merge_group:
    types: [checks_requested]

permissions: {}

jobs:
  cla-check:
    runs-on: ubuntu-latest
    steps:
      - name: Check if CLA signed
        uses: sharder996/has-signed-canonical-cla@patch-2
