name: Monitor USNs  # Ubuntu Security Notices

on:
  schedule:
  - cron: '0 5 * * *'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  ProcessUSNs:
    if: ${{ github.repository == 'canonical/multipass' }}

    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v5

    - name: Set up Python
      uses: actions/setup-python@v6
      with:
        python-version: '3.14'

    - name: Install Python dependencies
      uses: BSFishy/pip-action@v1
      with:
        requirements: tools/requirements.txt

    - name: Install Snap dependencies
      run: |
        sudo snap install review-tools

    - name: Set up Launchpad credentials
      uses: DamianReeves/write-file-action@v1.3
      with:
        path: lp_credentials
        contents: ${{ secrets.LAUNCHPAD_CREDENTIALS }}

    - name: Check for USNs
      run: tools/process-snaps/process_snaps.py lp_credentials
