#!/bin/sh
set -e

if [ ! -f  $SNAP_COMMON/libvirt/libvirtd.conf ]; then
    install -D $SNAP/var/snap/multipass/common/libvirt/libvirtd.conf $SNAP_COMMON/libvirt/libvirtd.conf
    sed -i 's/unix_sock_group = "libvirtd"/unix_sock_group = "sudo"/' $SNAP_COMMON/libvirt/libvirtd.conf
fi

if [ ! -d $SNAP_COMMON/run ]; then
    install --directory $SNAP_COMMON/run
fi
